### ISSUE TITLE
Mixing Row Major and Column Major

### ISSUE THREAD

**Issue by messej** [jeremyd85/dots_and_boxes#7]
Visualizer improperly handles asymmetric games:
stretches window along the wrong dimension

Board and/or Paper improperly handles asymmetric games:
causes index out of range error

**Comment by messej** [comment]
Paper.get_player_spots() is probably a culprit for the index errors

**Comment by messej** [comment]
an example of an issue
```py
height = 2
width = 3
x = [[x*(10**y) for x in range(1,width+1)] for y in range(height)]
y = np.array(x)
z = [(i // height, i % width) for i in range(width*height)]
print([y[ind] for ind in z])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 1, in <listcomp>
IndexError: index 2 is out of bounds for axis 0 with size 2```
